### ISSUE TITLE
Extension should have target toolchain

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustup.rs#664]
I get this panic from `rustup show`. I ran `rustup update` today and it succeeded but `show` started failing. I remember running `rustup show` almost immediately before `rustup update` and it worked. How can I fix this?

```
$ rustup show
Default host: x86_64-unknown-linux-gnu

thread '<main>' panicked at 'extension should have target toolchain', ../src/libcore/option.rs:699
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ RUST_BACKTRACE=1 rustup show
Default host: x86_64-unknown-linux-gnu

thread '<main>' panicked at 'extension should have target toolchain', ../src/libcore/option.rs:699
stack backtrace:
   1:     0x5652735d1a80 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x5652735d9d1b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x5652735d99a3 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x5652735bdd3f - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x5652735bf6c8 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
   6:     0x5652735d0e41 - rust_begin_unwind
   7:     0x5652736101bf - core::panicking::panic_fmt::h257ceb0aa351d801
   8:     0x565273617474 - core::option::expect_failed::h2d57a5644f345e0b
   9:     0x565273272f67 - rustup::toolchain::Toolchain::list_components::h6f5e5af7ff496961
  10:     0x5652731b1b44 - rustup_init::rustup_mode::show::hd748b4cc3a400485
  11:     0x565273188a8f - rustup_init::rustup_mode::main::h904c4ed7acbad99d
  12:     0x56527318336e - rustup_init::run_multirust::h70cbf6663515e18b
  13:     0x5652731824e1 - rustup_init::main::h81d74e5ca7cf36c2
  14:     0x5652735d95e4 - std::sys_common::unwind::try::try_fn::h04c0c89e4add6cc4
  15:     0x5652735d0dcb - __rust_try
  16:     0x5652735d902b - std::rt::lang_start::h61f4934e780b4dfc
  17:     0x7ffb2e80782f - __libc_start_main
  18:     0x5652731823d4 - <unknown>

$ rustup --version
rustup 0.5.0 (4be1012 2016-07-30)

$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.10.0-x86_64-unknown-linux-gnu
1.9.0-x86_64-unknown-linux-gnu
```

**Comment by dtolnay** [comment]
Blowing away `~/.multirust` does not fix it.

**Comment by brson** [comment]
This is due to a [change in the manifest format](https://github.com/rust-lang/rust-buildbot/pull/102). We'll try to get a fix out today.

**Comment by dtolnay** [comment]
For anyone watching this ticket - [Brian posted an update on internals.rust-lang.org](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/150?u=dtolnay).

**Comment by brson** [comment]
OK, planning on getting the fix deployed today now.

**Comment by brson** [comment]
Should be fixed with the latest release.

**Comment by dtolnay** [comment]
It is indeed fixed. Thanks!
